{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "openaev.fullname" $ }}-{{ .name }}
  labels:
    {{- include "openaev.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{- if regexMatch "\n" $value }}
  {{ $key }}: |
    {{ $value | nindent 4 | trim | b64enc }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{ end }}
