{{ if .Values.caldera.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openaev.fullname" . }}-caldera-config
  labels:
    {{- include "openaev.calderaLabels" . | nindent 4 }}
data:
  local.yml: |
    {{- .Values.caldera.config | toYaml | nindent 4 }}
{{ end }}
