{{- if .Values.caldera.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openaev.fullname" . }}-caldera
  labels:
    {{- include "openaev.calderaLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openaev.selectorCalderaLabels" . | nindent 6 }}
  {{- if .Values.caldera.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.caldera.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.caldera.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.caldera.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
