apiVersion: v2
name: openaev
description: A Helm chart to deploy Open Breach and Attack Simulation platform
icon: https://raw.githubusercontent.com/OpenCTI-Platform/docs/da9fcbaea4c1f02f86eca1bb8099876858082e13/docs/assets/images/favicon.png
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/devops-ia/helm-openaev
  - https://github.com/OpenAEV-Platform/openaev
version: 1.0.0
appVersion: 2.0.6
home: https://www.filigran.io/en/solutions/products/openaev/
keywords:
  - openaev
  - cybersecurity
  - purple-team
  - attack-simulation
  - breach-simulator
  - threat
  - analysis
dependencies:
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: opensearch
    version: 3.3.2
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.enabled
  - name: postgresql
    version: 16.7.27
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: rabbitmq
    version: 16.0.14
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled
